name: Hello World Action

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello World with Inputs
        run: echo "Hello, World! Input1 is: ${{ inputs.input1 }} and Input2 is: ${{ inputs.input2 }}"
        env:
          input1: ${{ inputs.input1 }}
          input2: ${{ inputs.input2 }}

  # Define inputs for the action
inputs:
  input1:
    description: 'The first input to print'
    required: true
    default: 'First Input Value'

  input2:
    description: 'The second input to print'
    required: true
    default: 'Second Input Value'