name: Hello World Action

on:
  workflow_call:
    inputs:
      input1:
        description: 'The first input'
        required: true
        default: 'First Input Value'
        type: string

      input2:
        description: 'The second input'
        required: true
        default: 'Second Input Value'
        type: string
  workflow_dispatch:
    inputs:
      input1:
        description: 'The first input'
        required: true
        default: 'First Input Value'

      input2:
        description: 'The second input'
        required: true
        default: 'Second Input Value'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello World with Inputs
        run: |
          echo "Hello, World! Input1 is: ${{ inputs.input1 }} and Input2 is: ${{ inputs.input2 }}"
        env:
          input1: ${{ inputs.input1 }}
          input2: ${{ inputs.input2 }}

